# Generated by Django 3.2.13 on 2024-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_answer_symptom_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='description',
            new_name='prevention',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='image',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_factors',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
