# Generated by Django 3.2.13 on 2024-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240526_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
