# Generated by Django 3.2.13 on 2024-06-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disease_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='risk_factors',
            new_name='description',
        ),
    ]
